sudo: required
services: 
  - docker

before_install: 
  - docker build -t fdesobry/react-test -f ./client/Dockerfile.dev ./client
script: 
  - docker run -e CI=true fdesobry/react-test npm run test
after_success: 
  - docker build -t fdesobry/multi-client ./client
  - docker build -t fdesobry/multi-server ./server
  - docker build -t fdesobry/multi-nginx ./nginx
  - docker build -t fdesobry/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push fdesobry/multi-client
  - docker push fdesobry/multi-server
  - docker push fdesobry/multi-nginx
  - docker push fdesobry/multi-worker