sudo: required
services: 
  - docker

before_install: 
  - docker build -t fdesobry/react-test -f ./client/Dockerfile.dev ./

script: docker run -r CI=true fdesobry/react-test npm run test

after_success: 
  - docker build fdesobry/multi-client ./client
  - docker build fdesobry/multi-server ./server
  - docker build fdesobry/multi-nginx ./nginx
  - docker build fdesobry/multi-worker ./worker
  - echo "$DOCKER_PASSOWRD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push fdesobry/multi-client
  - docker push fdesobry/multi-server
  - docker push fdesobry/multi-nginx
  - docker push fdesobry/multi-worker